name: Juniper Woodworks
favicon: null
layout_spectrum: 0.9390451544895768
typography_spectrum: 0.3568931841291487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6729233334772289
  lightness: 0.23141402564942837
  saturation: 0.5513550308533013
  rhythmicContrast: 0.8067780665587634
purpose: []
